spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/restaurant_db?createDatabaseIfNotExist=true"
    username: root
    password: 3010200530102005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: front-end
